http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'localhost'
  port: '27019'
  db_name: 'admin'
  username: 'root'
  password: 'qwerty'
  collection: 'tasks'