http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'mongodb'
  port: '27017'
  db_name: 'todo'
  username: 'mongo'
  password: 'mongo'
  collections:
    task: 'tasks'

test:
  db:
    host: 'localhost'
    port: '27018'
    db_name: 'test'
    collections:
      task: 'tasks'
